### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
Requires #56.

Also:

- [x] Needs `BROWSER_STACK_ACCESS_KEY` and `BROWSER_STACK_USERNAME` added in the repo secrets
- [x] Branch protection rules need to be adapted
- [x] Remove Travis CI from repo **integrations/apps/hooks**
- [x] Enable delete HEAD branches
- [x] Enable branches to be up to date
- [ ] I've yet to find a way to skip the BrowserStack tests like before with `[skip browser]`

### CODE REVIEW

**Comment by Johann-S** [comment]
Added BrowserStack keys here too

**Comment by XhmikosR** [comment]
Please take care of the rest of the TODO and also remove the secrets from the travis project before removing it :)

**Comment by XhmikosR** [comment]
It seems there's an error in IE 10:

>ERROR: 'This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.'

**Comment by XhmikosR** [comment]
...but tests aren't marked as failed. Are you sure everything works fine on IE 10? It's not related to this PR I think, I just noticed it now.

**Comment by Johann-S** [comment]
Done about the todo 👍 
Yep it's an error in the unit test libs but bs-custom-file-input works fine on IE 10

**Pull request merged**
